spring:
    profiles:
        active: local
    jpa:
        properties:
            jadira.usertype.autoRegisterUserTypes: true
    thymeleaf:
        cache: false
        mode: HTML
    servlet:
        multipart:
            max-request-size: 100MB
            max-file-size: 50MB
    main:
        allow-bean-definition-overriding: true  #Bean Overriding

server:
    port: 8099